/**
 * Created by Angine on 20/09/2025.
 */

public with sharing class CaseTriggerHandler {

    public void onBeforeInsert(List<Case> newList){

    }

    public void onBeforeUpdate(List<Case> newList, Map<Id, Case> oldMap){

    }

    public void onAfterInsert(List<Case> newList){

    }

    public void onAfterUpdate(List<Case> newList, Map<Id, Case> oldMap){

    }

    /*---------------------********************+******************---------------------*/

}